DROP TABLE IF EXISTS schedules;

CREATE TABLE IF NOT EXISTS schedules(

  user_id SERIAL PRIMARY KEY,
  username VARCHAR(80) NOT NULL,
  day VARCHAR(60) NOT NULL,
  start_at TIME NOT NULL,
  end_at TIME NOT NULL
);


