DROP TABLE IF EXISTS schedules;

CREATE TABLE IF NOT EXISTS schedules(
  id  SERIAL PRIMARY KEY,
  user_id VARCHAR(60) NOT NULL,
  day VARCHAR(60) NOT NULL,
  start_at TIME NOT NULL,
  end_at TIME NOT NULL


);